spring:
  # ConfiguraciÃ³n del datasource
  datasource:
    url: jdbc:h2:mem:renderdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # ConfiguraciÃ³n de JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # ðŸ‘ˆ corregido (no es H2DiaLect)

  sql:
    init:
      mode: never

# ConfiguraciÃ³n del servidor embebido (Tomcat)
server:
  port: 8080
